### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by gautierdag** [linkedtales/scrapedin#101]
LinkedIn has changed their layout to now have the `See all` button be a modal that displays the Interests (Companies, Groups, Schools).

This breaks `scrapedin` on `puppeteer==3.3.0` and `scrapedin==1.0.18`.

Tested on my own profile:
```js
const fs = require("fs");
const scrapedin = require("scrapedin");

async function main() {
  const linkedInUrl = "https://www.linkedin.com/in/gautier-dagan/";
  const cookies = fs.readFileSync("cookies.json");
  const options = {
    cookies: JSON.parse(cookies.toString()),
  };
  const profileScraper = await scrapedin(options);
  const linkedInProfile = await profileScraper(linkedInUrl);
  console.log(linkedInProfile);
}
main();
```

Returns:
```
UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/Users/tmp/scrapedin/node_modules/scrapedin/node_modules/puppeteer/lib/JSHandle.js:196:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ElementHandle.click (/Users/tmp/scrapedin/node_modules/scrapedin/node_modules/puppeteer/lib/JSHandle.js:248:20)
    at async scrapAccomplishmentPanel (/Users/tmp/scrapedin/node_modules/scrapedin/src/profile/scrapAccomplishmentPanel.js:10:5)
    at async module.exports (/Users/tmp/scrapedin/node_modules/scrapedin/src/profile/profile.js:50:19)
    at async main (/Users/tmp/scrapedin/index.js:14:27)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/tmp/scrapedin/node_modules/scrapedin/node_modules/puppeteer/lib/helper.js:108:27)
    at scrapAccomplishmentPanel (/Users/tmp/scrapedin/node_modules/scrapedin/src/profile/scrapAccomplishmentPanel.js:10:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/Users/tmp/scrapedin/node_modules/scrapedin/src/profile/profile.js:50:19)
    at async main (/Users/tmp/scrapedin/index.js:14:27)
```

**Comment by dgray0229** [comment]
I am having the same issue. when turning the log messages on I get this issue:
```
scrapedin: 2020-06-07T08:14:54.277Z warn: [profile/seeMoreButtons.js] couldn't click on button.pv-profile-section__see-more-inline, it's probably invisible
```
I double checked the classes just to make sure the selectors are correct, and they are. I'm not sure why the buttons can't be clicked. I also had isHeadless turned off.

**Comment by dgray0229** [comment]
I found a fork of this repo that fixes the node element issue. @getwanted has it on his profile. Here's the link:

https://github.com/wanted-hr/scrapedin

Just use npm or yarn to install his package and you should be good.

```
npm i @getwanted/scrapedin
const scrapedin = require ("@getwanted/scrapedin")
```

and stuff like that. maybe this will be accepted as a pull request eventually.

**Comment by gautierdag** [comment]
@dgray0229 Thanks for pointing out that branch. I came back to it and isolated the bug to the `.click` in the `scrapAccomplishmentsPanel.js` which is not present in the [scrapedin fork](https://github.com/wanted-hr/scrapedin) (hence why it works).

I've made a PR #108 that fixes the issue. Feel free to try it and comment if it also fixes the problem for you!

**Comment by dgray0229** [comment]
> @dgray0229 Thanks for pointing out that branch. I came back to it and isolated the bug to the `.click` in the `scrapAccomplishmentsPanel.js` which is not present in the [scrapedin fork](https://github.com/wanted-hr/scrapedin) (hence why it works).
> 
> I've made a PR #108 that fixes the issue. Feel free to try it and comment if it also fixes the problem for you!

I've tried out the repo that you've pulled in my project and the scrape works. No more errors. I can't wait for this to be pulled into the official module. Keep up the good work.
