### ISSUE TITLE
Error: LinkedIn website changed and scrapedin 1.0.18 can't read basic data

### ISSUE THREAD

**Issue by EmanFateen** [linkedtales/scrapedin#126]
I'm using scrapedin ver 1.0.18 on a dedicated server and it though this exception, however, this version works fine on my localhost   

> Error: LinkedIn website changed and scrapedin 1.0.18 can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
    at module.exports (/home/dummy/test.ai/crawler/node_modules/scrapedin/src/profile/cleanProfileData.js:13:11)
    at module.exports (/home/dummy/test.ai/crawler/node_modules/scrapedin/src/profile/profile.js:82:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Function.start (/home/dummy/test.ai/crawler/scraper.js:28:20)
    at async Socket.<anonymous> (/home/dummy/test.ai/crawler/scraper.js:48:5)

I'm logging by cookie and here is my settings 
scraper: {
		hasToLog: true,
		isHeadless: true,
		puppeteerArgs: {
			args: [
				'--no-sandbox'
			]
		},
		interval: 13000,
	}

and when I upgraded the scrapedin version to 1.0.20 on my localhost It through a new expectation :) I created an issue with this 
https://github.com/linkedtales/scrapedin/issues/125

No, the scrapedin doesn't work on my localhost with version 1.0.20 nighter on the server with version 1.0.18

Anyone can help, please?

**Comment by leonardiwagner** [comment]
solved on #125
