### ISSUE TITLE
Not able to deploy it in remote servers

### ISSUE THREAD

**Issue by anthonylai** [linkedtales/scrapedin#14]
Attempt to run it in a remote server like heroku, encountered this error:

(node:9167) UnhandledPromiseRejectionWarning: Error: linkedin: manual check was required, verify if your login is properly working man
ually or report this issue: https://github.com/leonardiwagner/scrapedin/issues
at page.waitFor.then.catch (/var/app/current/node_modules/scrapedin/src/login.js:62:31)
at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not
handled will terminate the Node.js process with a non-zero exit code.
(node:9167) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
at Promise (/var/app/current/node_modules/puppeteer/lib/Connection.js:183:56)
at new Promise ()
at CDPSession.send (/var/app/current/node_modules/puppeteer/lib/Connection.js:182:12)
at ExecutionContext.evaluateHandle (/var/app/current/node_modules/puppeteer/lib/ExecutionContext.js:106:44)
at ExecutionContext. (/var/app/current/node_modules/puppeteer/lib/helper.js:109:23)
at ElementHandle.$ (/var/app/current/node_modules/puppeteer/lib/JSHandle.js:378:50)
at ElementHandle. (/var/app/current/node_modules/puppeteer/lib/helper.js:109:23)
at DOMWorld.$ (/var/app/current/node_modules/puppeteer/lib/DOMWorld.js:114:34)
at process._tickCallback (internal/process/next_tick.js:68:7)
-- ASYNC --
at Frame. (/var/app/current/node_modules/puppeteer/lib/helper.js:108:27)
at Page.$ (/var/app/current/node_modules/puppeteer/lib/Page.js:300:29)
at Page. (/var/app/current/node_modules/puppeteer/lib/helper.js:109:23)
at page.waitFor.then.catch (/var/app/current/node_modules/scrapedin/src/login.js:60:16)
at process._tickCallback (internal/process/next_tick.js:68:7)

It is not possible to do manual verification as it is not possible to open a browser in such server and provide the verification. Is there any workaround to this issue?

**Comment by leonardiwagner** [comment]
Hi @anthonylai  , the manual check is usually required only once when you use a new device (such as a remote server),  and currently there is no feature in this project that answers this manual check automatically.

If your server has a graphical interface you can include the `isHeadless` parameter as `true` in the `scrapedin` Object along `email` and `password`, then resolve the manual check, and after doing that you can go back to the headless mode. (Please also increase the `waitTimeMs` in the `profileScraper` function for waiting you to complete the manual check)

**Comment by workdaylabs** [comment]
Thank you for the pointer.  I have switched over to aws and can open up the browser to get pass the manual check.

**Comment by anthonylai** [comment]
Thank you for the pointer. I have switched over to aws and can open up the browser to get pass the manual check.

**Comment by rizkiandrianto** [comment]
No fix for Heroku? @leonardiwagner @anthonylai ?

**Comment by leonardiwagner** [comment]
@rizkiandrianto Have you tried login via cookies? https://github.com/linkedtales/scrapedin/wiki/Using-Cookies-To-Login

**Comment by trns1997** [comment]
Hi guys,
A bit late to the game but for those of you stuck with heroku deployment I can confirm that login via cookies works.
