### ISSUE TITLE
Deploy in heroku - chrome error

### ISSUE THREAD

**Issue by fabianmedina09** [linkedtales/scrapedin#15]
First, Thank you for the time and the work you have used to develop that solution

I added code requested at "https://github.com/jontewks/puppeteer-heroku-buildpack" to use puppeteer

const args = proxyAddress && [`--proxy-server = $ {proxyAddress}`, '--no-sandbox', '--disable-setuid-sandbox']

But I get this error:
28 Feb 2019 05: 31: 29.549168 <190> 1 2019-02-28T10: 31: 28.908987 + 00: 00 app web.1 - - (node: 4) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
Heroku / Syslog drain
28 Feb 2019 05: 31: 29.549447 <190> 1 2019-02-28T10: 31: 28.909012 + 00: 00 app web.1 - - [0228 / 103126.902390: FATAL: zygote_host_impl_linux.cc (116)] Not usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Heroku / Syslog drain

Do you know any solution to this problem with the google kernel? I appreciate any help.

Regards

**Comment by leonardiwagner** [comment]
Hi @fabianmedina09 I don't have any experience with Heroku, but just wondering.. why to install 
[puppeteer-heroku-buildpack](https://github.com/jontewks/puppeteer-heroku-buildpack) ? Just `npm install` of this project isn't enough to run on Heroku (or in any server)?

What does happen when you just try to run Scrapedin without this extra package?

**Comment by fabianmedina09** [comment]
> Hi @fabianmedina09 I don't have any experience with Heroku, but just wondering.. why to install
> [puppeteer-heroku-buildpack](https://github.com/jontewks/puppeteer-heroku-buildpack) ? Just `npm install` of this project isn't enough to run on Heroku (or in any server)?
> 
> What does happen when you just try to run Scrapedin without this extra package?

I do not know the exact causes of why it is necessary to install it, it seems that the servers do not have some chrome libraries that allow their execution, but at the moment of executing it without that package, an error appears that subjects it to use it, I share it with you:

```
2019-03-01T04:46:46.834599+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
2019-03-01T04:46:46.834649+00:00 app[web.1]: [0301/044646.315954:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
2019-03-01T04:46:46.834652+00:00 app[web.1]: #0 0x55b2a425e8cf base::debug::StackTrace::StackTrace()
2019-03-01T04:46:46.834654+00:00 app[web.1]: #1 0x55b2a41d472e logging::LogMessage::~LogMessage()
2019-03-01T04:46:46.834656+00:00 app[web.1]: #2 0x55b2a57110be service_manager::ZygoteHostImpl::Init()
2019-03-01T04:46:46.834658+00:00 app[web.1]: #3 0x55b2a3e3329a content::ContentMainRunnerImpl::Initialize()
2019-03-01T04:46:46.834660+00:00 app[web.1]: #4 0x55b2a3e6530a service_manager::Main()
2019-03-01T04:46:46.834662+00:00 app[web.1]: #5 0x55b2a3e31861 content::ContentMain()
2019-03-01T04:46:46.834664+00:00 app[web.1]: #6 0x55b2a83f06a8 headless::(anonymous namespace)::RunContentMain()
2019-03-01T04:46:46.834666+00:00 app[web.1]: #7 0x55b2a83f0735 headless::HeadlessBrowserMain()
2019-03-01T04:46:46.834668+00:00 app[web.1]: #8 0x55b2a3e63d74 headless::HeadlessShellMain()
2019-03-01T04:46:46.834670+00:00 app[web.1]: #9 0x55b2a1e5a1ac ChromeMain
2019-03-01T04:46:46.834672+00:00 app[web.1]: #10 0x7ffabb311b97 __libc_start_main
2019-03-01T04:46:46.834674+00:00 app[web.1]: #11 0x55b2a1e5a02a _start
2019-03-01T04:46:46.834676+00:00 app[web.1]:
2019-03-01T04:46:46.834678+00:00 app[web.1]: Received signal 6
2019-03-01T04:46:46.834680+00:00 app[web.1]: #0 0x55b2a425e8cf base::debug::StackTrace::StackTrace()
2019-03-01T04:46:46.834681+00:00 app[web.1]: #1 0x55b2a425e441 base::debug::(anonymous namespace)::StackDumpSignalHandler()
2019-03-01T04:46:46.834683+00:00 app[web.1]: #2 0x7ffac1588890 <unknown>
2019-03-01T04:46:46.834685+00:00 app[web.1]: #3 0x7ffabb32ee97 gsignal
2019-03-01T04:46:46.834687+00:00 app[web.1]: #4 0x7ffabb330801 abort
2019-03-01T04:46:46.834689+00:00 app[web.1]: #5 0x55b2a425d285 base::debug::BreakDebugger()
2019-03-01T04:46:46.834691+00:00 app[web.1]: #6 0x55b2a41d4971 logging::LogMessage::~LogMessage()
2019-03-01T04:46:46.834692+00:00 app[web.1]: #7 0x55b2a57110be service_manager::ZygoteHostImpl::Init()
2019-03-01T04:46:46.834694+00:00 app[web.1]: #8 0x55b2a3e3329a content::ContentMainRunnerImpl::Initialize()
2019-03-01T04:46:46.834696+00:00 app[web.1]: #9 0x55b2a3e6530a service_manager::Main()
2019-03-01T04:46:46.834698+00:00 app[web.1]: #10 0x55b2a3e31861 content::ContentMain()
2019-03-01T04:46:46.834700+00:00 app[web.1]: #11 0x55b2a83f06a8 headless::(anonymous namespace)::RunContentMain()
2019-03-01T04:46:46.834702+00:00 app[web.1]: #12 0x55b2a83f0735 headless::HeadlessBrowserMain()
2019-03-01T04:46:46.834703+00:00 app[web.1]: #13 0x55b2a3e63d74 headless::HeadlessShellMain()
2019-03-01T04:46:46.834705+00:00 app[web.1]: #14 0x55b2a1e5a1ac ChromeMain
2019-03-01T04:46:46.834707+00:00 app[web.1]: #15 0x7ffabb311b97 __libc_start_main
2019-03-01T04:46:46.834709+00:00 app[web.1]: #16 0x55b2a1e5a02a _start
2019-03-01T04:46:46.834711+00:00 app[web.1]: r8: 0000000000000000  r9: 00007fffcc6d2020 r10: 0000000000000008 r11: 0000000000000246
2019-03-01T04:46:46.834713+00:00 app[web.1]: r12: 00007fffcc6d22c8 r13: 0000000000000161 r14: 00007fffcc6d2c30 r15: 00007fffcc6d2c28
2019-03-01T04:46:46.834714+00:00 app[web.1]: di: 0000000000000002  si: 00007fffcc6d2020  bp: 00007fffcc6d2270  bx: 00002ab65fa39800
2019-03-01T04:46:46.834716+00:00 app[web.1]: dx: 0000000000000000  ax: 0000000000000000  cx: 00007ffabb32ee97  sp: 00007fffcc6d2020
2019-03-01T04:46:46.834718+00:00 app[web.1]: ip: 00007ffabb32ee97 efl: 0000000000000246 cgf: 0000000000000033 erf: 0000000000000000
2019-03-01T04:46:46.834720+00:00 app[web.1]: trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
2019-03-01T04:46:46.834722+00:00 app[web.1]: [end of stack trace]
2019-03-01T04:46:46.834723+00:00 app[web.1]: Calling _exit(1). Core file will not be generated.
2019-03-01T04:46:46.834725+00:00 app[web.1]:
2019-03-01T04:46:46.834727+00:00 app[web.1]:
**2019-03-01T04:46:46.834729+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md**
2019-03-01T04:46:46.834730+00:00 app[web.1]:
2019-03-01T04:46:46.834732+00:00 app[web.1]: at onClose (/app/node_modules/puppeteer/lib/Launcher.js:360:14)
2019-03-01T04:46:46.834734+00:00 app[web.1]: at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:349:50)
2019-03-01T04:46:46.834737+00:00 app[web.1]: at emitNone (events.js:111:20)
2019-03-01T04:46:46.834738+00:00 app[web.1]: at Interface.emit (events.js:208:7)
2019-03-01T04:46:46.834740+00:00 app[web.1]: at Interface.close (readline.js:368:8)
2019-03-01T04:46:46.834742+00:00 app[web.1]: at Socket.onend (readline.js:147:10)
2019-03-01T04:46:46.834744+00:00 app[web.1]: at emitNone (events.js:111:20)
2019-03-01T04:46:46.834746+00:00 app[web.1]: at Socket.emit (events.js:208:7)
2019-03-01T04:46:46.834748+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1064:12)
2019-03-01T04:46:46.834749+00:00 app[web.1]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
2019-03-01T04:46:46.834927+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-03-01T04:46:46.835028+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fabianmedina09** [comment]
I can solve that with last version of "puppeteer": "^1.12.2";  and this:

`const browser = await puppeteer.launch({ headless: isHeadless, args})` **- Before**
`const browser = await puppeteer.launch({ headless: true, args:['--no-sandbox', '--disable-setuid-sandbox'] })` **-- After**

Now I have a problem of verification "manual" with Linkedin, they have sent me a PIN to my mail. I will try to solve it. Thank you

2019-03-01T05:32:50.908543+00:00 app[web.1]: at page.waitFor.then.catch (/app/controllers/scrapedin/login.js:60:16)
2019-03-01T05:32:50.908544+00:00 app[web.1]: at <anonymous>
2019-03-01T05:32:50.908546+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:188:7)
2019-03-01T05:32:50.908738+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-03-01T05:32:50.908830+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-03-01T05:32:50.910022+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Error: linkedin: manual check was required, verify if your login is properly working manually or report this issue: https://github.com/leonardiwagner/scrapedin/issues
2019-03-01T05:32:50.910025+00:00 app[web.1]: at page.waitFor.then.catch (/app/controllers/scrapedin/login.js:62:31)

**Comment by leonardiwagner** [comment]
> I can solve that with last version of "puppeteer": "^1.12.2"; and this:

Amazing @fabianmedina09 ! Feel free to open a pull request with that update

> Now I have a problem of verification "manual" with Linkedin, they have sent me a PIN to my mail. I will try to solve it. Thank you

This is something that I don't have a solution yet, since I don't know much how these manual check requirement works, but I'd try:

If they check by IP:
- Use a same VPN for both personal PC and remote server, and resolve manual check in your PC

If they check via cookies/useragent:
- Resolve manual check in the PC and store the cookies to share to the remote server 
puppeteer.

I think these both solutions combined can be a solution, please give us any feedback about that, thank you!

**Comment by leonardiwagner** [comment]
Now scrapedin `v1.0.6` has an option to pass to puppeteer the `--no-sandbox` without tweaking source code: https://github.com/linkedtales/scrapedin#documentation
