### ISSUE TITLE
(node:7117) UnhandledPromiseRejectionWarning: Error: Page crashed!

### ISSUE THREAD

**Issue by cyanide2019** [linkedtales/scrapedin#58]
(node:7117) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/home/scrapedin-linkedin-crawler/node_modules/scrapedin/node_modules/puppeteer/lib/Page.js:215:24)
    at CDPSession.Page.client.on.event (/home/scrapedin-linkedin-crawler/node_modules/scrapedin/node_modules/puppeteer/lib/Page.js:123:56)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/home/scrapedin-linkedin-crawler/node_modules/scrapedin/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/scrapedin-linkedin-crawler/node_modules/scrapedin/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/home/tony/scrapedin-linkedin-crawler/node_modules/scrapedin/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home//scrapedin-linkedin-crawler/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/tony/scrapedin-linkedin-crawler/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
(node:7117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by leonardiwagner** [comment]
is this happening always? for a specific profile? is it happening now?

It's a puppeteer library error, check if this issue helps: https://github.com/puppeteer/puppeteer/issues/1321

**Comment by leonardiwagner** [comment]
closed due to lack of feedback
