### ISSUE TITLE
Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by raphaelpreston** [linkedtales/scrapedin#94]
ScrapedIn Version: 1.0.16
Windows 10 Home Build: 18362.778
WSL: Ubuntu 18.04

Hopefully this isn't because I'm using @mNpenner's [creative fix](https://github.com/puppeteer/puppeteer/issues/1837#issuecomment-522850970) to get the puppeteer dependency to work (since I'm using WSL).

The browser successfully opens, logs into LinkedIn, navigates to the profile page, and scrolls down. That's when the error message is displayed.

Here's my code:

```javascript
const scrapedin = require('scrapedin')
const fs = require('fs')
const rimraf = require('del');

const PATHS = {
    win32: {
        executablePath: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
        userDataDir: 'C:\\Users\\<USER>\\AppData\\Local\\Temp\\puppeteer_user_data',
    },
    linux: {
        executablePath: "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe",
        userDataDir: '/mnt/c/Users/<USER>/AppData/Local/Temp/puppeteer_user_data',
    },
}

const cookies = fs.readFileSync('linkedincookie.json')
const options = {
  cookies: JSON.parse(cookies),
  puppeteerArgs: {
    executablePath: PATHS[process.platform].executablePath,
    userDataDir: PATHS.win32.userDataDir,
    headless: false,
  }
}

scrapedin(options)
.then((profileScraper) => profileScraper('https://www.linkedin.com/in/raphaelpreston/'))
.then((profile) => console.log(profile))
.finally(async () => {
    rimraf(PATHS[process.platform].userDataDir, {force: true}).then(() => {
        console.log("Deleted")
    })
}).catch(err => {
    console.error(err);
    process.exit(1);
});
```

The full error message:
```
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/mnt/c/Users/<USER>/<DIR>/node_modules/puppeteer/lib/JSHandle.js:196:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ElementHandle.click (/mnt/c/Users/<USER>/<DIR>/node_modules/puppeteer/lib/JSHandle.js:248:20)
    at async scrapAccomplishmentPanel (/mnt/c/Users/<USER>/<DIR>/node_modules/scrapedin/src/profile/scrapAccomplishmentPanel.js:10:5)
    at async module.exports (/mnt/c/Users/<USER>/<DIR>/node_modules/scrapedin/src/profile/profile.js:50:19)
  -- ASYNC --
    at ElementHandle.<anonymous> (/mnt/c/Users/<USER>/<DIR>/node_modules/puppeteer/lib/helper.js:108:27)
    at scrapAccomplishmentPanel (/mnt/c/Users/<USER>/<DIR>/node_modules/scrapedin/src/profile/scrapAccomplishmentPanel.js:10:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/mnt/c/Users/<USER>/<DIR>/node_modules/scrapedin/src/profile/profile.js:50:19)
```

This is my first time using a package that depends on Puppeteer, so let me know if there's something else I need to do to get stuff working.

**Comment by raphaelpreston** [comment]
After some more testing, I believe this error only occurs on _my own_ profile.

**Comment by raphaelpreston** [comment]
Just tested on `ceeb9eefca2efbe4caee889115ce7b25a50ade71`, unfortunately still broken. But I'm still only seeing this on my profile.

**Comment by leonardiwagner** [comment]
Thanks for reporting @raphaelpreston ! Honestly, I didn't look for fixing collecting our own profile data, I just placed a warning about not collecting it instead of throwing an error, that's on the new released version `v1.0.17`.

**Comment by leonardiwagner** [comment]
Related to #79 as error only occurs with own profile
